### ISSUE TITLE
How to generate data for classification?

### ISSUE THREAD

**Issue by monk1337** [chenzhaomin123/ML_GCN#11]
So the data which I downloaded looks like this : 

```
name,aeroplane,bicycle,bird,boat,bottle,bus,car,cat,chair,cow,diningtable,dog,horse,motorbike,person,pottedplant,sheep,sofa,train,tvmonitor

000048,-1,-1,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1,-1,-1,-1
000050,-1,-1,-1,-1,1,-1,-1,-1,0,-1,-1,-1,-1,-1,1,-1,-1,-1,-1,-1
000051,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,0,-1,-1,-1,-1,-1
```

I am confused about -1,1 and 0.

So if you are building one hot format ( if image is appearing under this category then 1 else -1 )
But then from where 0 is coming?

There are three labels -1 , 1 and 0 

Can you please explain this format?

Awesome work !

Thanks.

**Comment by chenzhaomin123** [comment]
We set all 0 labels to -1.

**Comment by monk1337** [comment]
@chenzhaomin123  so basically it's negative one hot encoding 

If label is in image then 1 else -1 

Still why there are few 0's in label? and why -1 any specific reason to choose -1 ,1 instead of 0 and 1 ?

Thank you for your quick reply.

**Comment by chenzhaomin123** [comment]
0 means difficult label, we just ignore all these labels.
you can see [http://host.robots.ox.ac.uk/pascal/VOC/voc2007/guidelines.html](url) for details.
