### ISSUE TITLE
training probelm

### ISSUE THREAD

**Issue by 2014gaokao** [chenzhaomin123/ML_GCN#15]
Training: 100%|██████████| 2506/2506
Epoch: [0]	Loss 0.6480	mAP 7.513
OP: 0.3080	OR: 0.0587	OF1: 0.0986	CP: 0.0750	CR: 0.0138	CF1: 0.0233

I did not use pretrain models, this is what i get after training. how strange the results are...

**Comment by HannibalXing** [comment]
> Training: 100%|██████████| 2506/2506
> Epoch: [0]	Loss 0.6480	mAP 7.513
> OP: 0.3080	OR: 0.0587	OF1: 0.0986	CP: 0.0750	CR: 0.0138	CF1: 0.0233
> 
> I did not use pretrain models, this is what i get after training. how strange the results are...

I think the paper mentioned 100 epoch, you just trained 1 epoch?  Also May I ask you which GPU do you use to train this model. I used NV-1080, but it shows the GPU out of memory issue. Thanks

**Comment by HannibalXing** [comment]
> Training: 100%|██████████| 2506/2506
> Epoch: [0]	Loss 0.6480	mAP 7.513
> OP: 0.3080	OR: 0.0587	OF1: 0.0986	CP: 0.0750	CR: 0.0138	CF1: 0.0233
> 
> I did not use pretrain models, this is what i get after training. how strange the results are...

I got it, the author trained with Multiple GPUs.
