### ISSUE TITLE
when will you release the paper?

### ISSUE THREAD

**Issue by mensaochun** [chenzhaomin123/ML_GCN#2]

**Comment by usernoproblem** [comment]
Dear Mensaochun,
I have read the paper " Deep Imbalanced Attribute Classification using Visual Attention Aggregation" that you comment. I sent email for you (953558652@qq.com). You can reply.
Thank you so much !!
github: https://github.com/cvcode18/imbalanced_learning

**Comment by liugl7** [comment]
+1

**Comment by nxsEdson** [comment]
+1

**Comment by chenzhaomin123** [comment]
https://arxiv.org/abs/1904.03582

**Comment by monk1337** [comment]
@chenzhaomin123  can you please take a look?

https://github.com/chenzhaomin123/ML_GCN/issues/11
