### ISSUE TITLE
Can you share your code of generating adjacent matrix?

### ISSUE THREAD

**Issue by miaoshuyu** [chenzhaomin123/ML_GCN#7]
This work is so amazing, Can you share your code of generating adjacent matrix?

**Comment by Abhinav43** [comment]
+1

If I want to use my own data how can I generate adj matrix?

**Comment by cgpeter96** [comment]
按着论文上的公式算就行了 ，如果学过分词的话一看就懂。
先统计标签间的共现次数，然后利用公式6 得到概率矩阵
然后按着7,8来做就行
